image:
  # image.parentRepository -- Docker registry to pull images from
  parentRepository: gcr.io/jenkinsxio

  # image.tag -- Docker images tag
  tag: 0.0.104

  # image.pullPolicy -- Image pull policy
  pullPolicy: IfNotPresent

gcJobs:
  # gcJobs.schedule -- Cron expression to periodically delete `Preview`s
  schedule: "0/30 * * * *"

  # gcJobs.failedJobsHistoryLimit -- Drives the failed jobs history limit
  failedJobsHistoryLimit: 1

  # gcJobs.successfulJobsHistoryLimit -- Drives the successful jobs history limit
  successfulJobsHistoryLimit: 3

  # gcJobs.concurrencyPolicy -- Drives the job's concurrency policy
  concurrencyPolicy: Forbid

  image:
    # gcJobs.image.repository -- Template for computing the gc job docker image repository
    repository: "{{ .Values.image.parentRepository }}/jx-preview"

    # gcJobs.image.tag -- Template for computing the gc job docker image tag
    tag: "{{ .Values.image.tag }}"

    # gcJobs.image.pullPolicy -- Template for computing the gc job docker image pull policy
    pullPolicy: "{{ .Values.image.pullPolicy }}"


